alter table LDAP_LDAP_CONFIG add CONTEXT_SOURCE_BASE varchar(255)^

alter table LDAP_LDAP_CONFIG add CONTEXT_SOURCE_URL varchar(255)^

alter table LDAP_LDAP_CONFIG add CONTEXT_SOURCE_USER_NAME varchar(255)^

alter table LDAP_LDAP_CONFIG add CONTEXT_SOURCE_PASSWORD varchar(255)^

